name: parachain-docker-template

on:
  push:
    branches:  [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        working-directory: ./parachain
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        working-directory: parachain
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        working-directory: ${{env.working-directory}}
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1 
#        working-directory: ${{env.working-directory}}
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        working-directory: ${{env.working-directory}}
        with:
          push: false
          tags: integritee/parachain-template:latest
