name: parachain-docker-template

on:
  push:
    branches:  [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: integritee/parachain-template
  
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
        working-directory: ./parachain
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./parachain
          file: ./parachain/Dockerfile
          push: true
          tags: ${{env.IMAGE_NAME}}:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        

